spring:
  jpa:
    generate-ddl: true
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  rabbitmq:
    addresses: localhost:5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
    ssl:
      enabled: false

statistics:
  rabbitmq:
    exchangeName: "request.exchange"
    queueName: "request.queue"
    routingKey: "key"
